// SPDX-License-Identifier: BUSL-1.1
pragma solidity ^0.8.28;

import {IMethodReentrancyTest} from "../interfaces/IMethodReentrancyTest.sol";
import {IMethodsRegistry} from "../interfaces/IMethodsRegistry.sol";

import {AccrueInterestReentrancyTest} from "../methods/silo/AccrueInterestReentrancyTest.sol";
import {AccrueInterestForConfigReentrancyTest} from "../methods/silo/AccrueInterestForConfigReentrancyTest.sol";
import {AllowanceReentrancyTest} from "../methods/silo/AllowanceReentrancyTest.sol";
import {ApproveReentrancyTest} from "../methods/silo/ApproveReentrancyTest.sol";
import {AssetReentrancyTest} from "../methods/silo/AssetReentrancyTest.sol";
import {BalanceOfAndTotalSupplyReentrancyTest} from "../methods/silo/BalanceOfAndTotalSupplyReentrancyTest.sol";
import {BalanceOfReentrancyTest} from "../methods/silo/BalanceOfReentrancyTest.sol";
import {BorrowReentrancyTest} from "../methods/silo/BorrowReentrancyTest.sol";
import {BorrowSameAssetReentrancyTest} from "../methods/silo/BorrowSameAssetReentrancyTest.sol";
import {BorrowSharesReentrancyTest} from "../methods/silo/BorrowSharesReentrancyTest.sol";
import {BurnReentrancyTest} from "../methods/silo/BurnReentrancyTest.sol";
import {CallOnBehalfOfSiloReentrancyTest} from "../methods/silo/CallOnBehalfOfSiloReentrancyTest.sol";
import {ConfigReentrancyTest} from "../methods/silo/ConfigReentrancyTest.sol";
import {ConvertToAssetsReentrancyTest} from "../methods/silo/ConvertToAssetsReentrancyTest.sol";
import {ConvertToAssetsWithTypeReentrancyTest} from "../methods/silo/ConvertToAssetsWithTypeReentrancyTest.sol";
import {ConvertToSharesReentrancyTest} from "../methods/silo/ConvertToSharesReentrancyTest.sol";
import {ConvertToSharesWithTypeReentrancyTest} from "../methods/silo/ConvertToSharesWithTypeReentrancyTest.sol";
import {DecimalsReentrancyTest} from "../methods/silo/DecimalsReentrancyTest.sol";
import {DepositReentrancyTest} from "../methods/silo/DepositReentrancyTest.sol";
import {DepositWithTypeReentrancyTest} from "../methods/silo/DepositWithTypeReentrancyTest.sol";
import {DomainSeparatorReentrancyTest} from "../methods/silo/DomainSeparatorReentrancyTest.sol";
import {Eip712DomainReentrancyTest} from "../methods/silo/Eip712DomainReentrancyTest.sol";
import {FactoryReentrancyTest} from "../methods/silo/FactoryReentrancyTest.sol";
import {FlashFeeReentrancyTest} from "../methods/silo/FlashFeeReentrancyTest.sol";
import {FlashLoanReentrancyTest} from "../methods/silo/FlashLoanReentrancyTest.sol";
import {ForwardTransferFromNoChecksTest} from "../methods/silo/ForwardTransferFromNoChecksTest.sol";
import {GetCollateralAndDebtTotalsStorageReentrancyTest} from "../methods/silo/GetCollateralAndDebtTotalsStorageReentrancyTest.sol";
import {GetCollateralAndProtectedTotalsStorageReentrancyTest}
    from "../methods/silo/GetCollateralAndProtectedTotalsStorageReentrancyTest.sol";
import {GetCollateralAssetsReentrancyTest} from "../methods/silo/GetCollateralAssetsReentrancyTest.sol";
import {GetDebtAssetsReentrancyTest} from "../methods/silo/GetDebtAssetsReentrancyTest.sol";
import {GetLiquidityReentrancyTest} from "../methods/silo/GetLiquidityReentrancyTest.sol";
import {HookReceiverTokenReentrancyTest} from "../methods/silo/HookReceiverTokenReentrancyTest.sol";
import {HookSetupReentrancyTest} from "../methods/silo/HookSetupReentrancyTest.sol";
import {InitializeReentrancyTest} from "../methods/silo/InitializeReentrancyTest.sol";
import {IsSolventReentrancyTest} from "../methods/silo/IsSolventReentrancyTest.sol";
import {MaxBorrowReentrancyTest} from "../methods/silo/MaxBorrowReentrancyTest.sol";
import {MaxBorrowSameAssetReentrancyTest} from "../methods/silo/MaxBorrowSameAssetReentrancyTest.sol";
import {MaxBorrowSharesReentrancyTest} from "../methods/silo/MaxBorrowSharesReentrancyTest.sol";
import {MaxDepositReentrancyTest} from "../methods/silo/MaxDepositReentrancyTest.sol";
import {MaxDepositWithTypeReentrancyTest} from "../methods/silo/MaxDepositWithTypeReentrancyTest.sol";
import {MaxFlashLoanReentrancyTest} from "../methods/silo/MaxFlashLoanReentrancyTest.sol";
import {MaxMintReentrancyTest} from "../methods/silo/MaxMintReentrancyTest.sol";
import {MaxMintWithTypeReentrancyTest} from "../methods/silo/MaxMintWithTypeReentrancyTest.sol";
import {MaxRedeemReentrancyTest} from "../methods/silo/MaxRedeemReentrancyTest.sol";
import {MaxRedeemWithTypeReentrancyTest} from "../methods/silo/MaxRedeemWithTypeReentrancyTest.sol";
import {MaxRepayReentrancyTest} from "../methods/silo/MaxRepayReentrancyTest.sol";
import {MaxRepaySharesReentrancyTest} from "../methods/silo/MaxRepaySharesReentrancyTest.sol";
import {MaxWithdrawReentrancyTest} from "../methods/silo/MaxWithdrawReentrancyTest.sol";
import {MaxWithdrawWithTypeReentrancyTest} from "../methods/silo/MaxWithdrawWithTypeReentrancyTest.sol";
import {MintReentrancyTest} from "../methods/silo/MintReentrancyTest.sol";
import {MintTokenReentrancyTest} from "../methods/silo/MintTokenReentrancyTest.sol";
import {MintWithTypeReentrancyTest} from "../methods/silo/MintWithTypeReentrancyTest.sol";
import {NameReentrancyTest} from "../methods/silo/NameReentrancyTest.sol";
import {NoncesReentrancyTest} from "../methods/silo/NoncesReentrancyTest.sol";
import {PermitReentrancyTest} from "../methods/silo/PermitReentrancyTest.sol";
import {PreviewBorrowReentrancyTest} from "../methods/silo/PreviewBorrowReentrancyTest.sol";
import {PreviewBorrowSharesReentrancyTest} from "../methods/silo/PreviewBorrowSharesReentrancyTest.sol";
import {PreviewDepositReentrancyTest} from "../methods/silo/PreviewDepositReentrancyTest.sol";
import {PreviewDepositWithTypeReentrancyTest} from "../methods/silo/PreviewDepositWithTypeReentrancyTest.sol";
import {PreviewMintReentrancyTest} from "../methods/silo/PreviewMintReentrancyTest.sol";
import {PreviewMintWithTypeReentrancyTest} from "../methods/silo/PreviewMintWithTypeReentrancyTest.sol";
import {PreviewRedeemReentrancyTest} from "../methods/silo/PreviewRedeemReentrancyTest.sol";
import {PreviewRedeemWithTypeReentrancyTest} from "../methods/silo/PreviewRedeemWithTypeReentrancyTest.sol";
import {PreviewRepayReentrancyTest} from "../methods/silo/PreviewRepayReentrancyTest.sol";
import {PreviewRepaySharesReentrancyTest} from "../methods/silo/PreviewRepaySharesReentrancyTest.sol";
import {PreviewWithdrawReentrancyTest} from "../methods/silo/PreviewWithdrawReentrancyTest.sol";
import {PreviewWithdrawWithTypeReentrancyTest} from "../methods/silo/PreviewWithdrawWithTypeReentrancyTest.sol";
import {RedeemReentrancyTest} from "../methods/silo/RedeemReentrancyTest.sol";
import {RedeemWithTypeReentrancyTest} from "../methods/silo/RedeemWithTypeReentrancyTest.sol";
import {RepayReentrancyTest} from "../methods/silo/RepayReentrancyTest.sol";
import {RepaySharesReentrancyTest} from "../methods/silo/RepaySharesReentrancyTest.sol";
import {SiloConfigReentrancyTest} from "../methods/silo/SiloConfigReentrancyTest.sol";
import {GetSiloStorageReentrancyTest} from "../methods/silo/GetSiloStorageReentrancyTest.sol";
import {SiloReentrancyTest} from "../methods/share-token/SiloReentrancyTest.sol";
import {SiloTokenReentrancyTest} from "../methods/silo/SiloTokenReentrancyTest.sol";
import {SwitchCollateralToThisSiloReentrancyTest} from "../methods/silo/SwitchCollateralToThisSiloReentrancyTest.sol";
import {SymbolReentrancyTest} from "../methods/silo/SymbolReentrancyTest.sol";
import {SynchronizeHooksReentrancyTest} from "../methods/share-token/SynchronizeHooksReentrancyTest.sol";
import {SynchronizeHooksTokenReentrancyTest} from "../methods/silo/SynchronizeHooksTokenReentrancyTest.sol";
import {GetTotalAssetsStorageReentrancyTest} from "../methods/silo/GetTotalAssetsStorageReentrancyTest.sol";
import {TotalAssetsReentrancyTest} from "../methods/silo/TotalAssetsReentrancyTest.sol";
import {TotalSupplyReentrancyTest} from "../methods/silo/TotalSupplyReentrancyTest.sol";
import {TransferReentrancyTest} from "../methods/silo/TransferReentrancyTest.sol";
import {TransferFromReentrancyTest} from "../methods/silo/TransferFromReentrancyTest.sol";
import {TransitionCollateralReentrancyTest} from "../methods/silo/TransitionCollateralReentrancyTest.sol";
import {UpdateHooksReentrancyTest} from "../methods/silo/UpdateHooksReentrancyTest.sol";
import {UtilizationDataReentrancyTest} from "../methods/silo/UtilizationDataReentrancyTest.sol";
import {WithdrawReentrancyTest} from "../methods/silo/WithdrawReentrancyTest.sol";
import {WithdrawWithTypeReentrancyTest} from "../methods/silo/WithdrawWithTypeReentrancyTest.sol";
import {WithdrawFeesReentrancyTest} from "../methods/silo/WithdrawFeesReentrancyTest.sol";

contract SiloMethodsRegistry is IMethodsRegistry {
    mapping(bytes4 methodSig => IMethodReentrancyTest) public methods;
    bytes4[] public supportedMethods;

    constructor() {
        _registerMethod(new AccrueInterestReentrancyTest());
        _registerMethod(new AccrueInterestForConfigReentrancyTest());
        _registerMethod(new AllowanceReentrancyTest());
        _registerMethod(new ApproveReentrancyTest());
        _registerMethod(new AssetReentrancyTest());
        _registerMethod(new BalanceOfAndTotalSupplyReentrancyTest());
        _registerMethod(new BalanceOfReentrancyTest());
        _registerMethod(new BorrowReentrancyTest());
        _registerMethod(new BorrowSameAssetReentrancyTest());
        _registerMethod(new BorrowSharesReentrancyTest());
        _registerMethod(new BurnReentrancyTest());
        _registerMethod(new CallOnBehalfOfSiloReentrancyTest());
        _registerMethod(new ConfigReentrancyTest());
        _registerMethod(new ConvertToAssetsReentrancyTest());
        _registerMethod(new ConvertToAssetsWithTypeReentrancyTest());
        _registerMethod(new ConvertToSharesReentrancyTest());
        _registerMethod(new ConvertToSharesWithTypeReentrancyTest());
        _registerMethod(new DecimalsReentrancyTest());
        _registerMethod(new DepositReentrancyTest());
        _registerMethod(new DepositWithTypeReentrancyTest());
        _registerMethod(new DomainSeparatorReentrancyTest());
        _registerMethod(new Eip712DomainReentrancyTest());
        _registerMethod(new FactoryReentrancyTest());
        _registerMethod(new FlashFeeReentrancyTest());
        _registerMethod(new FlashLoanReentrancyTest());
        _registerMethod(new ForwardTransferFromNoChecksTest());
        _registerMethod(new GetCollateralAndDebtTotalsStorageReentrancyTest());
        _registerMethod(new GetCollateralAndProtectedTotalsStorageReentrancyTest());
        _registerMethod(new GetCollateralAssetsReentrancyTest());
        _registerMethod(new GetDebtAssetsReentrancyTest());
        _registerMethod(new GetLiquidityReentrancyTest());
        _registerMethod(new HookReceiverTokenReentrancyTest());
        _registerMethod(new HookSetupReentrancyTest());
        _registerMethod(new InitializeReentrancyTest());
        _registerMethod(new IsSolventReentrancyTest());
        _registerMethod(new MaxBorrowReentrancyTest());
        _registerMethod(new MaxBorrowSameAssetReentrancyTest());
        _registerMethod(new MaxBorrowSharesReentrancyTest());
        _registerMethod(new MaxDepositReentrancyTest());
        _registerMethod(new MaxDepositWithTypeReentrancyTest());
        _registerMethod(new MaxFlashLoanReentrancyTest());
        _registerMethod(new MaxMintReentrancyTest());
        _registerMethod(new MaxMintWithTypeReentrancyTest());
        _registerMethod(new MaxRedeemReentrancyTest());
        _registerMethod(new MaxRedeemWithTypeReentrancyTest());
        _registerMethod(new MaxRepayReentrancyTest());
        _registerMethod(new MaxRepaySharesReentrancyTest());
        _registerMethod(new MaxWithdrawReentrancyTest());
        _registerMethod(new MaxWithdrawWithTypeReentrancyTest());
        _registerMethod(new MintReentrancyTest());
        _registerMethod(new MintTokenReentrancyTest());
        _registerMethod(new MintWithTypeReentrancyTest());
        _registerMethod(new NameReentrancyTest());
        _registerMethod(new NoncesReentrancyTest());
        _registerMethod(new PermitReentrancyTest());
        _registerMethod(new PreviewBorrowReentrancyTest());
        _registerMethod(new PreviewBorrowSharesReentrancyTest());
        _registerMethod(new PreviewDepositReentrancyTest());
        _registerMethod(new PreviewDepositWithTypeReentrancyTest());
        _registerMethod(new PreviewMintReentrancyTest());
        _registerMethod(new PreviewMintWithTypeReentrancyTest());
        _registerMethod(new PreviewRedeemReentrancyTest());
        _registerMethod(new PreviewRedeemWithTypeReentrancyTest());
        _registerMethod(new PreviewRepayReentrancyTest());
        _registerMethod(new PreviewRepaySharesReentrancyTest());
        _registerMethod(new PreviewWithdrawReentrancyTest());
        _registerMethod(new PreviewWithdrawWithTypeReentrancyTest());
        _registerMethod(new RedeemReentrancyTest());
        _registerMethod(new RedeemWithTypeReentrancyTest());
        _registerMethod(new RepayReentrancyTest());
        _registerMethod(new RepaySharesReentrancyTest());
        _registerMethod(new SiloConfigReentrancyTest());
        _registerMethod(new GetSiloStorageReentrancyTest());
        _registerMethod(new SiloReentrancyTest());
        _registerMethod(new SiloTokenReentrancyTest());
        _registerMethod(new SwitchCollateralToThisSiloReentrancyTest());
        _registerMethod(new SymbolReentrancyTest());
        _registerMethod(new SynchronizeHooksReentrancyTest());
        _registerMethod(new SynchronizeHooksTokenReentrancyTest());
        _registerMethod(new GetTotalAssetsStorageReentrancyTest());
        _registerMethod(new TotalAssetsReentrancyTest());
        _registerMethod(new TotalSupplyReentrancyTest());
        _registerMethod(new TransferReentrancyTest());
        _registerMethod(new TransferFromReentrancyTest());
        _registerMethod(new TransitionCollateralReentrancyTest());
        _registerMethod(new UpdateHooksReentrancyTest());
        _registerMethod(new UtilizationDataReentrancyTest());
        _registerMethod(new WithdrawReentrancyTest());
        _registerMethod(new WithdrawWithTypeReentrancyTest());
        _registerMethod(new WithdrawFeesReentrancyTest());
    }

    function supportedMethodsLength() external view returns (uint256) {
        return supportedMethods.length;
    }

    function abiFile() external pure returns (string memory) {
        return "/cache/foundry/out/silo-core/Silo.sol/Silo.json";
    }

    function _registerMethod(IMethodReentrancyTest method) internal {
        methods[method.methodSignature()] = method;
        supportedMethods.push(method.methodSignature());
    }
}
