# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Hooks Quality Test

env:
    RPC_ARBITRUM: ${{ secrets.RPC_ARBITRUM }}

on:
    push:
        branches: [ master, develop ]

    pull_request:

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3

            -   name: Install Foundry
                uses: foundry-rs/foundry-toolchain@v1
                with:
                    version: nightly-70cd140131cd49875c6f31626bdfae08eba35386

            -   name: Install Foundry
                uses: foundry-rs/foundry-toolchain@v1
                with:
                    version: nightly-70cd140131cd49875c6f31626bdfae08eba35386

            -   name: run tests
                run: forge test -vv
