# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Oracles Quality Test

env:
  FOUNDRY_PROFILE: oracles
  RPC_MAINNET: ${{ secrets.RPC_MAINNET }}
  RPC_ARBITRUM: ${{ secrets.RPC_ARBITRUM }}
  RPC_OPTIMISM: ${{ secrets.RPC_OPTIMISM }}
  RPC_SONIC: ${{ secrets.RPC_SONIC }}
  RPC_ANVIL: ${{ secrets.RPC_ANVIL }}
  PRIVATE_KEY: ${{ secrets.ANVIL_PRIVATE_KEY }}

on:
  push:
    branches: [ master, develop ]
    paths:
      - silo-oracles/**/*.sol
      - silo-oracles/**/*.ts
      - silo-oracles/**/*.js
      - silo-oracles/**/*.json
      - silo-core/contracts/interfaces/ISiloOracle.sol
      - package.json
      - yarn.lock
      - gitmodules/*
      - .gitmodules
      - .github/workflows/silo-oracles.yml

  pull_request:
    paths:
      - silo-oracles/**/*.sol
      - silo-oracles/**/*.ts
      - silo-oracles/**/*.js
      - silo-oracles/**/*.json
      - silo-core/contracts/interfaces/ISiloOracle.sol
      - package.json
      - yarn.lock
      - gitmodules/*
      - .gitmodules
      - .github/workflows/silo-oracles.yml

jobs:

  linters:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: yarn install

      - name: Solidity Lint
        run: yarn workspace silo-oracles lint:sol

  foundry:
    name: Foundry QA
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-70cd140131cd49875c6f31626bdfae08eba35386

      - name: Build silo foundry utils
        working-directory: ./gitmodules/silo-foundry-utils
        run: |
          cargo build --release
          cp target/release/silo-foundry-utils ../../silo-foundry-utils
          ../../silo-foundry-utils --version

      - name: Run Forge build
        run: |
          git submodule
          forge --version
          FOUNDRY_PROFILE=oracles forge build --sizes

      - name: Run Forge tests
        run: FOUNDRY_PROFILE=oracles forge test -vv --no-match-test "_skip_" --ffi
